In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# AND Gate

In [3]:
weight1 = 0.5
weight2 = 0.5
bias = -1

In [4]:
test_inputs = [(0,0), (0,1), (1,0), (1,1)]
correct_outputs = [False, False, False, True]
outputs = []

for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = 1 if linear_combination >= 0 else 0
    is_correct_string = "Yes" if output == correct_output else "No"
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])
    
num_wrong = len([output[4] for output in outputs if output[4] == "No"])
output_frame = pd.DataFrame(outputs, columns=["Input 1", "Input 2", "Linear Combination", "Activation Output", "Is Correc"])

if not num_wrong:
    print(f"Nice! You got everything correct. \n")
else:
    print(f"You got {num_wrong} wrong. Keep trying. \n")

output_frame.head()

Nice! You got everything correct.

   Input 1  Input 2  Linear Combination  Activation Output Is Correc
0        0        0                -1.0                  0       Yes
1        0        1                -0.5                  0       Yes
2        1        0                -0.5                  0       Yes
3        1        1                 0.0                  1       Yes

# OR Gate

In [5]:
weight1 = 0.5
weight2 = 0.5
bias = -0.5

In [6]:
test_inputs = [(0,0), (0,1), (1,0), (1,1)]
correct_outputs = [False, True, True, True]
outputs = []

for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = 1 if linear_combination >= 0 else 0
    is_correct_string = "Yes" if output == correct_output else "No"
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])
    
num_wrong = len([output[4] for output in outputs if output[4] == "No"])
output_frame = pd.DataFrame(outputs, columns=["Input 1", "Input 2", "Linear Combination", "Activation Output", "Is Correc"])

if not num_wrong:
    print(f"Nice! You got everything correct. \n")
else:
    print(f"You got {num_wrong} wrong. Keep trying. \n")

output_frame.head()

Nice! You got everything correct.

   Input 1  Input 2  Linear Combination  Activation Output Is Correc
0        0        0                -0.5                  0       Yes
1        0        1                 0.0                  1       Yes
2        1        0                 0.0                  1       Yes
3        1        1                 0.5                  1       Yes

# XOR Gate

In [ ]:
weight1 = -0.5
weight2 = -0.5
bias = 1

In [ ]:
test_inputs = [(0,0), (0,1), (1,0), (1,1)]
correct_outputs = [False, True, True, False]
outputs = []

for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = 1 if not (linear_combination == 0 or linear_combination == 1) else 0
    is_correct_string = "Yes" if output == correct_output else "No"
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])
    
num_wrong = len([output[4] for output in outputs if output[4] == "No"])
output_frame = pd.DataFrame(outputs, columns=["Input 1", "Input 2", "Linear Combination", "Activation Output", "Is Correc"])

if not num_wrong:
    print(f"Nice! You got everything correct. \n")
else:
    print(f"You got {num_wrong} wrong. Keep trying. \n")

output_frame.head()

Nice! You got everything correct.

   Input 1  Input 2  Linear Combination  Activation Output Is Correc
0        0        0                 1.0                  0       Yes
1        0        1                 0.5                  1       Yes
2        1        0                 0.5                  1       Yes
3        1        1                 0.0                  0       Yes

# NOT Gate

In [13]:
weight1 = 0
weight2 = -1.5
bias = 1

In [14]:
test_inputs = [(0,0), (0,1), (1,0), (1,1)]
correct_outputs = [True, False, True, False]
outputs = []

for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = 1 if linear_combination >= 0 else 0
    is_correct_string = "Yes" if output == correct_output else "No"
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])
    
num_wrong = len([output[4] for output in outputs if output[4] == "No"])
output_frame = pd.DataFrame(outputs, columns=["Input 1", "Input 2", "Linear Combination", "Activation Output", "Is Correc"])

if not num_wrong:
    print(f"Nice! You got everything correct. \n")
else:
    print(f"You got {num_wrong} wrong. Keep trying. \n")

output_frame.head()

Nice! You got everything correct.

   Input 1  Input 2  Linear Combination  Activation Output Is Correc
0        0        0                 1.0                  1       Yes
1        0        1                -0.5                  0       Yes
2        1        0                 1.0                  1       Yes
3        1        1                -0.5                  0       Yes

# NOR Gate

In [15]:
weight1 = -1
weight2 = -1
bias = 0.5

In [16]:
test_inputs = [(0,0), (0,1), (1,0), (1,1)]
correct_outputs = [True, False, False, False]
outputs = []

for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = 1 if linear_combination >= 0 else 0
    is_correct_string = "Yes" if output == correct_output else "No"
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])
    
num_wrong = len([output[4] for output in outputs if output[4] == "No"])
output_frame = pd.DataFrame(outputs, columns=["Input 1", "Input 2", "Linear Combination", "Activation Output", "Is Correc"])

if not num_wrong:
    print(f"Nice! You got everything correct. \n")
else:
    print(f"You got {num_wrong} wrong. Keep trying. \n")

output_frame.head()

Nice! You got everything correct.

   Input 1  Input 2  Linear Combination  Activation Output Is Correc
0        0        0                 0.5                  1       Yes
1        0        1                -0.5                  0       Yes
2        1        0                -0.5                  0       Yes
3        1        1                -1.5                  0       Yes

# NAND Gate