In [20]:
import pandas as pd

In [ ]:
df = pd.read_csv("data/SAFI_openrefine.csv")
df

,interview_date,quest_no,start,end,province,district,ward,village,years_farm,agr_assoc,...,items_owned,items_owned_other,no_meals,months_lack_food,no_food_mitigation,gps_Latitude,gps_Longitude,gps_Altitude,gps_Accuracy,instanceID
0,17-Nov-16,1,2017-03-23T09:49:57.000Z,2017-04-02T17:29:08.000Z,Manica,Manica,Bandula,God,11,no,...,['bicycle' ; 'television' ; 'solar_panel' ; ...,NaN,2,['Jan'],['na' ; 'rely_less_food' ; 'reduce_meals' ; ...,-19.112259,33.483456,698,14.0,uuid:ec241f2c-0609-46ed-b5e8-fe575f6cefef
1,17-Nov-16,1,2017-04-02T09:48:16.000Z,2017-04-02T17:26:19.000Z,Manica,Manica,Bandula,God,2,yes,...,['cow_cart' ; 'bicycle' ; 'radio' ; 'cow_pl...,NaN,2,['Jan' ; 'Sept' ; 'Oct' ; 'Nov' ; 'Dec'],['na' ; 'reduce_meals' ; 'restrict_adults' ;...,-19.112477,33.483416,690,19.0,uuid:099de9c9-3e5e-427b-8452-26250e840d6e
2,17-Nov-16,3,2017-04-02T14:35:26.000Z,2017-04-02T17:26:53.000Z,Manica,Manica,Bandula,God,40,no,...,['solar_torch'],NaN,2,['Jan' ; 'Feb' ; 'Mar' ; 'Oct' ; 'Nov' ; ...,['na' ; 'restrict_adults' ; 'lab_ex_food'],-19.112108,33.483450,674,13.0,uuid:193d7daf-9582-409b-bf09-027dd36f9007
3,17-Nov-16,4,2017-04-02T14:55:18.000Z,2017-04-02T17:27:16.000Z,Manica,Manica,Bandula,God,6,no,...,['bicycle' ; 'radio' ; 'cow_plough' ; 'sola...,NaN,2,['Sept' ; 'Oct' ; 'Nov' ; 'Dec'],['na' ; 'reduce_meals' ; 'restrict_adults' ;...,-19.112229,33.483424,679,5.0,uuid:148d1105-778a-4755-aa71-281eadd4a973
4,17-Nov-16,5,2017-04-02T15:10:35.000Z,2017-04-02T17:27:35.000Z,Manica,Manica,Bandula,God,18,no,...,['motorcyle' ; 'radio' ; 'cow_plough' ; 'mo...,NaN,2,['Aug' ; 'Sept' ; 'Oct' ; 'Nov'],['na' ; 'go_forest' ; 'migrate'],-19.112217,33.483425,689,10.0,uuid:2c867811-9696-4966-9866-f35c3e97d02d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,18-May-17,126,2017-05-18T04:13:37.000Z,2017-05-18T04:35:47.000Z,Manica,Manica,Bandula,Ruaca,5,yes,...,['motorcyle' ; 'radio' ; 'solar_panel'],NaN,3,['Oct' ; 'Nov' ; 'Dec'],['rely_less_food' ; 'lab_ex_food'],-19.112194,33.483379,700,7.0,uuid:69caea81-a4e5-4e8d-83cd-9c18d8e8d965
127,4-Jun-17,193,2017-06-04T09:36:20.000Z,2017-06-04T10:13:32.000Z,Manica,Manica,Bandula,Ruaca,10,no,...,['car' ; 'lorry' ; 'television' ; 'radio' ;...,NaN,3,['none'],['na'],-19.112157,33.483390,720,9.0,uuid:5ccc2e5a-ea90-48b5-8542-69400d5334df
128,4-Jun-17,194,2017-06-04T10:13:36.000Z,2017-06-04T10:32:06.000Z,Manica,Manica,Bandula,Ruaca,5,no,...,['radio' ; 'solar_panel' ; 'solar_torch' ; ...,NaN,3,['Sept' ; 'Oct' ; 'Nov'],['lab_ex_food'],-19.112271,33.483471,719,10.0,uuid:95c11a30-d44f-40c4-8ea8-ec34fca6bbbf
129,4-Jun-17,199,2017-06-04T10:33:55.000Z,2017-06-04T10:52:22.000Z,Manica,Manica,Bandula,Chirodzo,17,yes,...,['cow_cart' ; 'lorry' ; 'motorcyle' ; 'comp...,NaN,3,['Nov' ; 'Dec'],['rely_less_food' ; 'limit_variety' ; 'reduc...,-19.112278,33.483390,711,5.0,uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b
130,4-Jun-17,200,2017-06-04T10:52:46.000Z,2017-06-04T11:08:13.000Z,Manica,Manica,Bandula,Chirodzo,20,yes,...,['radio' ; 'cow_plough' ; 'solar_panel' ; '...,NaN,3,['Oct' ; 'Nov'],['rely_less_food' ; 'restrict_adults' ; 'bor...,-19.112183,33.483372,681,20.0,uuid:aa77a0d7-7142-41c8-b494-483a5b68d8a7

In [22]:
df.isnull()

,interview_date,quest_no,start,end,province,district,ward,village,years_farm,agr_assoc,...,items_owned,items_owned_other,no_meals,months_lack_food,no_food_mitigation,gps_Latitude,gps_Longitude,gps_Altitude,gps_Accuracy,instanceID
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
128,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
129,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
130,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [24]:
df = df.drop(columns=["items_owned_other"])
df

,interview_date,quest_no,start,end,province,district,ward,village,years_farm,agr_assoc,...,du_look_aftr_cows,items_owned,no_meals,months_lack_food,no_food_mitigation,gps_Latitude,gps_Longitude,gps_Altitude,gps_Accuracy,instanceID
0,17-Nov-16,1,2017-03-23T09:49:57.000Z,2017-04-02T17:29:08.000Z,Manica,Manica,Bandula,God,11,no,...,no,['bicycle' ; 'television' ; 'solar_panel' ; ...,2,['Jan'],['na' ; 'rely_less_food' ; 'reduce_meals' ; ...,-19.112259,33.483456,698,14.0,uuid:ec241f2c-0609-46ed-b5e8-fe575f6cefef
1,17-Nov-16,1,2017-04-02T09:48:16.000Z,2017-04-02T17:26:19.000Z,Manica,Manica,Bandula,God,2,yes,...,no,['cow_cart' ; 'bicycle' ; 'radio' ; 'cow_pl...,2,['Jan' ; 'Sept' ; 'Oct' ; 'Nov' ; 'Dec'],['na' ; 'reduce_meals' ; 'restrict_adults' ;...,-19.112477,33.483416,690,19.0,uuid:099de9c9-3e5e-427b-8452-26250e840d6e
2,17-Nov-16,3,2017-04-02T14:35:26.000Z,2017-04-02T17:26:53.000Z,Manica,Manica,Bandula,God,40,no,...,no,['solar_torch'],2,['Jan' ; 'Feb' ; 'Mar' ; 'Oct' ; 'Nov' ; ...,['na' ; 'restrict_adults' ; 'lab_ex_food'],-19.112108,33.483450,674,13.0,uuid:193d7daf-9582-409b-bf09-027dd36f9007
3,17-Nov-16,4,2017-04-02T14:55:18.000Z,2017-04-02T17:27:16.000Z,Manica,Manica,Bandula,God,6,no,...,no,['bicycle' ; 'radio' ; 'cow_plough' ; 'sola...,2,['Sept' ; 'Oct' ; 'Nov' ; 'Dec'],['na' ; 'reduce_meals' ; 'restrict_adults' ;...,-19.112229,33.483424,679,5.0,uuid:148d1105-778a-4755-aa71-281eadd4a973
4,17-Nov-16,5,2017-04-02T15:10:35.000Z,2017-04-02T17:27:35.000Z,Manica,Manica,Bandula,God,18,no,...,no,['motorcyle' ; 'radio' ; 'cow_plough' ; 'mo...,2,['Aug' ; 'Sept' ; 'Oct' ; 'Nov'],['na' ; 'go_forest' ; 'migrate'],-19.112217,33.483425,689,10.0,uuid:2c867811-9696-4966-9866-f35c3e97d02d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,18-May-17,126,2017-05-18T04:13:37.000Z,2017-05-18T04:35:47.000Z,Manica,Manica,Bandula,Ruaca,5,yes,...,no,['motorcyle' ; 'radio' ; 'solar_panel'],3,['Oct' ; 'Nov' ; 'Dec'],['rely_less_food' ; 'lab_ex_food'],-19.112194,33.483379,700,7.0,uuid:69caea81-a4e5-4e8d-83cd-9c18d8e8d965
127,4-Jun-17,193,2017-06-04T09:36:20.000Z,2017-06-04T10:13:32.000Z,Manica,Manica,Bandula,Ruaca,10,no,...,no,['car' ; 'lorry' ; 'television' ; 'radio' ;...,3,['none'],['na'],-19.112157,33.483390,720,9.0,uuid:5ccc2e5a-ea90-48b5-8542-69400d5334df
128,4-Jun-17,194,2017-06-04T10:13:36.000Z,2017-06-04T10:32:06.000Z,Manica,Manica,Bandula,Ruaca,5,no,...,no,['radio' ; 'solar_panel' ; 'solar_torch' ; ...,3,['Sept' ; 'Oct' ; 'Nov'],['lab_ex_food'],-19.112271,33.483471,719,10.0,uuid:95c11a30-d44f-40c4-8ea8-ec34fca6bbbf
129,4-Jun-17,199,2017-06-04T10:33:55.000Z,2017-06-04T10:52:22.000Z,Manica,Manica,Bandula,Chirodzo,17,yes,...,no,['cow_cart' ; 'lorry' ; 'motorcyle' ; 'comp...,3,['Nov' ; 'Dec'],['rely_less_food' ; 'limit_variety' ; 'reduc...,-19.112278,33.483390,711,5.0,uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b
130,4-Jun-17,200,2017-06-04T10:52:46.000Z,2017-06-04T11:08:13.000Z,Manica,Manica,Bandula,Chirodzo,20,yes,...,no,['radio' ; 'cow_plough' ; 'solar_panel' ; '...,3,['Oct' ; 'Nov'],['rely_less_food' ; 'restrict_adults' ; 'bor...,-19.112183,33.483372,681,20.0,uuid:aa77a0d7-7142-41c8-b494-483a5b68d8a7

In [26]:
df.drop(columns=["no_food_mitigation", "gps_Altitude"])

,interview_date,quest_no,start,end,province,district,ward,village,years_farm,agr_assoc,...,liv_count,poultry,du_look_aftr_cows,items_owned,no_meals,months_lack_food,gps_Latitude,gps_Longitude,gps_Accuracy,instanceID
0,17-Nov-16,1,2017-03-23T09:49:57.000Z,2017-04-02T17:29:08.000Z,Manica,Manica,Bandula,God,11,no,...,1,yes,no,['bicycle' ; 'television' ; 'solar_panel' ; ...,2,['Jan'],-19.112259,33.483456,14.0,uuid:ec241f2c-0609-46ed-b5e8-fe575f6cefef
1,17-Nov-16,1,2017-04-02T09:48:16.000Z,2017-04-02T17:26:19.000Z,Manica,Manica,Bandula,God,2,yes,...,3,yes,no,['cow_cart' ; 'bicycle' ; 'radio' ; 'cow_pl...,2,['Jan' ; 'Sept' ; 'Oct' ; 'Nov' ; 'Dec'],-19.112477,33.483416,19.0,uuid:099de9c9-3e5e-427b-8452-26250e840d6e
2,17-Nov-16,3,2017-04-02T14:35:26.000Z,2017-04-02T17:26:53.000Z,Manica,Manica,Bandula,God,40,no,...,1,yes,no,['solar_torch'],2,['Jan' ; 'Feb' ; 'Mar' ; 'Oct' ; 'Nov' ; ...,-19.112108,33.483450,13.0,uuid:193d7daf-9582-409b-bf09-027dd36f9007
3,17-Nov-16,4,2017-04-02T14:55:18.000Z,2017-04-02T17:27:16.000Z,Manica,Manica,Bandula,God,6,no,...,2,yes,no,['bicycle' ; 'radio' ; 'cow_plough' ; 'sola...,2,['Sept' ; 'Oct' ; 'Nov' ; 'Dec'],-19.112229,33.483424,5.0,uuid:148d1105-778a-4755-aa71-281eadd4a973
4,17-Nov-16,5,2017-04-02T15:10:35.000Z,2017-04-02T17:27:35.000Z,Manica,Manica,Bandula,God,18,no,...,4,yes,no,['motorcyle' ; 'radio' ; 'cow_plough' ; 'mo...,2,['Aug' ; 'Sept' ; 'Oct' ; 'Nov'],-19.112217,33.483425,10.0,uuid:2c867811-9696-4966-9866-f35c3e97d02d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,18-May-17,126,2017-05-18T04:13:37.000Z,2017-05-18T04:35:47.000Z,Manica,Manica,Bandula,Ruaca,5,yes,...,3,yes,no,['motorcyle' ; 'radio' ; 'solar_panel'],3,['Oct' ; 'Nov' ; 'Dec'],-19.112194,33.483379,7.0,uuid:69caea81-a4e5-4e8d-83cd-9c18d8e8d965
127,4-Jun-17,193,2017-06-04T09:36:20.000Z,2017-06-04T10:13:32.000Z,Manica,Manica,Bandula,Ruaca,10,no,...,3,no,no,['car' ; 'lorry' ; 'television' ; 'radio' ;...,3,['none'],-19.112157,33.483390,9.0,uuid:5ccc2e5a-ea90-48b5-8542-69400d5334df
128,4-Jun-17,194,2017-06-04T10:13:36.000Z,2017-06-04T10:32:06.000Z,Manica,Manica,Bandula,Ruaca,5,no,...,1,no,no,['radio' ; 'solar_panel' ; 'solar_torch' ; ...,3,['Sept' ; 'Oct' ; 'Nov'],-19.112271,33.483471,10.0,uuid:95c11a30-d44f-40c4-8ea8-ec34fca6bbbf
129,4-Jun-17,199,2017-06-04T10:33:55.000Z,2017-06-04T10:52:22.000Z,Manica,Manica,Bandula,Chirodzo,17,yes,...,2,yes,no,['cow_cart' ; 'lorry' ; 'motorcyle' ; 'comp...,3,['Nov' ; 'Dec'],-19.112278,33.483390,5.0,uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b
130,4-Jun-17,200,2017-06-04T10:52:46.000Z,2017-06-04T11:08:13.000Z,Manica,Manica,Bandula,Chirodzo,20,yes,...,3,yes,no,['radio' ; 'cow_plough' ; 'solar_panel' ; '...,3,['Oct' ; 'Nov'],-19.112183,33.483372,20.0,uuid:aa77a0d7-7142-41c8-b494-483a5b68d8a7

In [ ]:
df2 = pd.read_csv("data/SAFI_clean.csv")
df2

,key_ID,village,interview_date,no_membrs,years_liv,respondent_wall_type,rooms,memb_assoc,affect_conflicts,liv_count,items_owned,no_meals,months_lack_food,instanceID
0,1,God,2016-11-17T00:00:00Z,3,4,muddaub,1,NaN,NaN,1,bicycle;television;solar_panel;table,2,Jan,uuid:ec241f2c-0609-46ed-b5e8-fe575f6cefef
1,1,God,2016-11-17T00:00:00Z,7,9,muddaub,1,yes,once,3,cow_cart;bicycle;radio;cow_plough;solar_panel;...,2,Jan;Sept;Oct;Nov;Dec,uuid:099de9c9-3e5e-427b-8452-26250e840d6e
2,3,God,2016-11-17T00:00:00Z,10,15,burntbricks,1,NaN,NaN,1,solar_torch,2,Jan;Feb;Mar;Oct;Nov;Dec,uuid:193d7daf-9582-409b-bf09-027dd36f9007
3,4,God,2016-11-17T00:00:00Z,7,6,burntbricks,1,NaN,NaN,2,bicycle;radio;cow_plough;solar_panel;mobile_phone,2,Sept;Oct;Nov;Dec,uuid:148d1105-778a-4755-aa71-281eadd4a973
4,5,God,2016-11-17T00:00:00Z,7,40,burntbricks,1,NaN,NaN,4,motorcyle;radio;cow_plough;mobile_phone,2,Aug;Sept;Oct;Nov,uuid:2c867811-9696-4966-9866-f35c3e97d02d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,126,Ruaca,2017-05-18T00:00:00Z,3,7,burntbricks,1,no,more_once,3,motorcyle;radio;solar_panel,3,Oct;Nov;Dec,uuid:69caea81-a4e5-4e8d-83cd-9c18d8e8d965
127,193,Ruaca,2017-06-04T00:00:00Z,7,10,cement,3,no,more_once,3,car;lorry;television;radio;sterio;cow_plough;s...,3,none,uuid:5ccc2e5a-ea90-48b5-8542-69400d5334df
128,194,Ruaca,2017-06-04T00:00:00Z,4,5,muddaub,1,no,more_once,1,radio;solar_panel;solar_torch;mobile_phone,3,Sept;Oct;Nov,uuid:95c11a30-d44f-40c4-8ea8-ec34fca6bbbf
129,199,Chirodzo,2017-06-04T00:00:00Z,7,17,burntbricks,2,yes,more_once,2,cow_cart;lorry;motorcyle;computer;television;r...,3,Nov;Dec,uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b
130,200,Chirodzo,2017-06-04T00:00:00Z,8,20,burntbricks,2,NaN,NaN,3,radio;cow_plough;solar_panel;solar_torch;table...,3,Oct;Nov,uuid:aa77a0d7-7142-41c8-b494-483a5b68d8a7

In [28]:
df2.isnull()

,key_ID,village,interview_date,no_membrs,years_liv,respondent_wall_type,rooms,memb_assoc,affect_conflicts,liv_count,items_owned,no_meals,months_lack_food,instanceID
0,False,False,False,False,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,False,False,False,False,False,False,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,False,False,False,False
128,False,False,False,False,False,False,False,False,False,False,False,False,False,False
129,False,False,False,False,False,False,False,False,False,False,False,False,False,False
130,False,False,False,False,False,False,False,True,True,False,False,False,False,False

In [29]:
df2.dropna()

,key_ID,village,interview_date,no_membrs,years_liv,respondent_wall_type,rooms,memb_assoc,affect_conflicts,liv_count,items_owned,no_meals,months_lack_food,instanceID
1,1,God,2016-11-17T00:00:00Z,7,9,muddaub,1,yes,once,3,cow_cart;bicycle;radio;cow_plough;solar_panel;...,2,Jan;Sept;Oct;Nov;Dec,uuid:099de9c9-3e5e-427b-8452-26250e840d6e
6,7,God,2016-11-17T00:00:00Z,6,38,muddaub,1,no,never,1,motorcyle;cow_plough,3,Nov,uuid:ae20a58d-56f4-43d7-bafa-e7963d850844
7,8,Chirodzo,2016-11-16T00:00:00Z,12,70,burntbricks,3,yes,never,2,motorcyle;bicycle;television;radio;cow_plough;...,2,Jan,uuid:d6cee930-7be1-4fd9-88c0-82a08f90fb5a
8,9,Chirodzo,2016-11-16T00:00:00Z,8,6,burntbricks,1,no,never,3,television;solar_panel;solar_torch,3,Jan;Dec,uuid:846103d2-b1db-4055-b502-9cd510bb7b37
9,10,Chirodzo,2016-12-16T00:00:00Z,12,23,burntbricks,5,no,never,2,cow_cart;motorcyle;bicycle;television;radio;co...,3,Jan;Oct;Nov;Dec,uuid:8f4e49bc-da81-4356-ae34-e0d794a23721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,192,Chirodzo,2017-06-03T00:00:00Z,9,20,burntbricks,1,no,once,1,bicycle;television;radio;sterio;solar_panel;so...,3,Jan;Nov;Dec,uuid:f94409a6-e461-4e4c-a6fb-0072d3d58b00
126,126,Ruaca,2017-05-18T00:00:00Z,3,7,burntbricks,1,no,more_once,3,motorcyle;radio;solar_panel,3,Oct;Nov;Dec,uuid:69caea81-a4e5-4e8d-83cd-9c18d8e8d965
127,193,Ruaca,2017-06-04T00:00:00Z,7,10,cement,3,no,more_once,3,car;lorry;television;radio;sterio;cow_plough;s...,3,none,uuid:5ccc2e5a-ea90-48b5-8542-69400d5334df
128,194,Ruaca,2017-06-04T00:00:00Z,4,5,muddaub,1,no,more_once,1,radio;solar_panel;solar_torch;mobile_phone,3,Sept;Oct;Nov,uuid:95c11a30-d44f-40c4-8ea8-ec34fca6bbbf
129,199,Chirodzo,2017-06-04T00:00:00Z,7,17,burntbricks,2,yes,more_once,2,cow_cart;lorry;motorcyle;computer;television;r...,3,Nov;Dec,uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b

In [33]:
def oldest_farm(x):
    x = df["years_farm"].max()
    output = "The oldest farm is " + str(x)
    return output
df3 = df["years_farm"].apply(oldest_farm)
print(df3)

0      The oldest farm is 60
1      The oldest farm is 60
2      The oldest farm is 60
3      The oldest farm is 60
4      The oldest farm is 60
               ...
126    The oldest farm is 60
127    The oldest farm is 60
128    The oldest farm is 60
129    The oldest farm is 60
130    The oldest farm is 60
Name: years_farm, Length: 131, dtype: object